[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4.9.0"
# argon2-kdf = "1.5.4"
argon2-kdf = { git = "https://github.com/lucascompython/argon2-kdf", branch = "main" }
env_logger = { version = "0.11.6", optional = true }
mimalloc = "0.1.43"
sonic-rs = "0.3.17"

[features]
default = []
log = ["env_logger"]


[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.
