[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.0"
actix-multipart = { version = "0.7.2", default-features = false, features = [
    "derive",
] }
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4.9.0"
ahash = "0.8.11"
argon2-kdf = { git = "https://github.com/lucascompython/argon2-kdf", branch = "main" }
chrono = { version = "0.4.40", default-features = false, features = [
    "std",
    "clock",
    "now",
] }
env_logger = { version = "0.11.6", optional = true }
futures-core = "0.3"
futures-util = "0.3"
mimalloc = "0.1.43"
papaya = "0.2.0"
serde = { version = "1.0.218", features = ["derive"] }
sonic-rs = "0.3.17"
sqlx = { version = "0.8.3", default-features = false, features = [
    "runtime-tokio",
    "mysql",
    "macros",
    "chrono",
] }
tokio = { version = "1", features = ["macros"] }

[features]
default = []
log = ["env_logger"]


[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.
